keys:
  - &personal_age_key age17wtyk7xgfllwv3yjj4ww422k6hxywkckfmdnyagu74xnrpmr0upqxa4ce2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *personal_age_key
  - path_regex: secrets/binary/.*$
    key_groups:
      - pgp:
          - *personal_age_key
