main_user_passwd_hash: ENC[AES256_GCM,data:5NHOnIPiYqifuKKqVFSIzxoxwziaUgq+Iqi5pDS0Ym9BRrSklL/RA4el/IfM9XqgQWVEolAIjDmPVjlRCRIIpUIjLpd5GTyPug==,iv:reqO+s1PiUdSvpOYuVtwGOx8dpdhvRAnZcI/kI5GoT4=,tag:hFYoxLZHcrBo0rfL50mpJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17wtyk7xgfllwv3yjj4ww422k6hxywkckfmdnyagu74xnrpmr0upqxa4ce2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TmEyT1d0VExjTTJRQnI4
            akdlKzlPeWdZTGZqVEl4dStvKzNaTCsyYkFzClNRYWlkbmdrbE96dUdpczNWejla
            QWgybmpacFNmNmVCblBNU0pOQ2ZKVXcKLS0tIG9WNE5xZElzYm9qeEcrbmc2dUto
            RzB1eVFOOVhsbzl1NThVTXBtaGtBaVEKT2710wJve0QqPxsqyVf8eqZ/D61+R/ql
            YKV4eI/C4HRTc+6nErBTWZ4EIaQwoChAEmIY0fx83s9dJSrY8enfMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T15:02:47Z"
    mac: ENC[AES256_GCM,data:ADyt3DaGSpJKv7FaBctZYok7KPBT8t1AzLg9fJX3KLZU36I+I5Xxc76iq6KjbZdUS995XlERffKvkngEFoUN7dDJM2ExzT2OhjjPpyuCZoX4JNcqsDN3WlD0JQn2wh8PJzS4yOuS3JcYR9dzFVcDKibmEiJhjLBcJ8zkwHEMcC8=,iv:eE9VA8iIG21DJROjDPCZNXApVwbQiDNjBiWwfQYCTdQ=,tag:p6XjwLs4p8e855YJOZW7jw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
